name: Update README with recent activity

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # 👈 Necesario para que GITHUB_TOKEN tenga permiso de escribir

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: zkjon
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MSG: 'chore: updated GitHub activity'
          MAX_LINES: 5
          TARGET_FILE: README.md
          EMPTY_COMMIT_MSG: ':memo: empty commit to keep workflow active after 60 days of no activity'
