name: Update README with recent activity

on:
  schedule:
    - cron: '0 * * * *'  # cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: 'chore: updated GitHub activity'
